In [11]:
import numpy as np

# Ejercicio 1
ej1 = np.zeros(10)
print("Ej1:", ej1)

Ej1: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Ejercicio 2
ej2 = np.arange(1, 21)
print("Ej2:", ej2)



Ej2: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [4]:
# Ejercicio 3
ej3 = np.arange(2, 51, 2)
print("Ej3:", ej3)


Ej3: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [5]:
# Ejercicio 4
ej4 = np.random.rand(4,4)
print("Ej4:\n", ej4)

Ej4:
 [[0.18019417 0.84031238 0.7511129  0.48691479]
 [0.26083553 0.4121987  0.83983251 0.43926639]
 [0.92085892 0.64408096 0.97431971 0.21936379]
 [0.75458872 0.34744751 0.49257837 0.26105736]]


In [6]:
# Ejercicio 5
a = np.array([1,2,3])
b = np.array([4,5,6])
ej6 = a + b
print("Ej5:", ej5)

Ej5: [[0.29044975 0.37070436 0.40211209 0.65190548]
 [0.41582421 0.81599339 0.41832408 0.9766027 ]
 [0.831119   0.07235802 0.922241   0.97935097]
 [0.40371497 0.58563686 0.04197234 0.99087673]]


In [7]:
# Ejercicio 6
m1 = np.random.randint(1, 11, (3,3))
m2 = np.random.randint(1, 11, (3,3))
ej7 = np.dot(m1, m2)
print("Matriz 1:\n", m1)
print("Matriz 2:\n", m2)
print("Ej6 (multiplicación):\n", ej6)

Matriz 1:
 [[8 8 4]
 [9 3 7]
 [2 8 6]]
Matriz 2:
 [[ 8  4  4]
 [ 1  8 10]
 [ 2  4  2]]
Ej6 (multiplicación):
 [5 7 9]


In [8]:
# Ejercicio 7
ej8 = np.random.randint(1, 101, 15)
print("Ej7:", ej7)
print("Máximo:", np.max(ej8))
print("Mínimo:", np.min(ej8))
print("Promedio:", np.mean(ej8))

Ej7: [[ 80 112 120]
 [ 89  88  80]
 [ 36  96 100]]
Máximo: 99
Mínimo: 2
Promedio: 52.0


In [9]:
# Ejercicio 8
ej9 = np.arange(1, 26).reshape(5,5)
diagonal = np.diag(ej9)
print("Ej8:\n", ej8)
print("Diagonal:", diagonal)

Ej8:
 [ 9 39 31  2 84 86 44 87 72 79 33 62 17 99 36]
Diagonal: [ 1  7 13 19 25]


In [10]:
# Ejercicio 9
mat = np.random.randint(1, 21, (5,5))
print("Matriz:\n", mat)
print("Suma filas:", np.sum(mat, axis=1))
print("Suma columnas:", np.sum(mat, axis=0))


Matriz:
 [[14 15 17  5 11]
 [ 4 20 19  5  9]
 [20  3  6 11  7]
 [ 6  4 10  9 10]
 [16  3 19  6 20]]
Suma filas: [62 57 47 39 64]
Suma columnas: [60 45 71 36 57]
